version: '3'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "8080:8080"
    volumes:
      - ../frontend:/app_frontend
    networks:
      - webapp
    restart: always
    container_name: frontend_app

networks:
  webapp:
    driver: bridge
